### PR TITLE
Removed unneccessary setting of length of arraybuffer

### PR DESCRIPTION
**Pull request by khankuan**

### CODE REVIEW

**Comment by SheetJSDev** [comment]
@khankuan The underlying buffer in the decode function is reused between calls to avoid numerous allocations of small buffers.  That particular length assignment is important since it is used in the toString call to determine which bytes of the buffer are used in the encoding (the default behavior of the toString function uses the buffer's length field as the end index).

It might be preferable to explicitly specify the end in the function call itself, like `mdb.toString('ucs2', 0, 2 * len);`, but somewhere the length has to be specified

**Comment by khankuan** [comment]
Hmm ic. The problem occurred when I was in strict mode. It says that the buffer length is a read-only property (at least on chrome). When I removed that line, the library works as normal for my particular use case.

**Comment by SheetJSDev** [comment]
@khankuan do you have a small example?  That particular line should not be triggered in Chrome because the `Buffer` is not generally available and [the global check](https://github.com/khankuan/js-codepage/blob/efb228ab757f51fb3b3422d41deb718ee3de8aef/cputils.js#L36-L37) should prevent that logic from being called in the first place

**Comment by SheetJSDev** [comment]
This should be fixed in version 1.4.0

**Pull request closed without merging**
